name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build (PHP ${{ matrix.php }}, Go ${{ matrix.go }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        go: [1.13, 1.14]
        os: [ubuntu-latest]
    env:
      GO111MODULE: on

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: xdebug

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show versions
        run: php -v ; composer -V ; go version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check code style
        run: vendor_php/bin/spiral-cs check src tests

      - name: Get dependencies
        run: go mod download

      - name: Build Go
        run: go build -v .

      - name: Run test suite
        run: |
          vendor_php/bin/phpunit

      - name: Run code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if [[ "$CODECOV_TOKEN" != "" ]]; then
            curl https://codecov.io/bash -o codecov-bash
            chmod +x codecov-bash
          fi
